const url = [
  {
    id: 1,
    title: 'EBBC 98.1 FM',
    artist: 'ABAKALIKI',
    artwork: require('../assets/img/ebbc.png'),
    url: 'https://chima.radioca.st/stream',
  },
  {
    id: 2,
    title: 'COOL FM 96.9 FM',
    artist: 'LAGOS',
    artwork: require('../assets/img/coolfm.png'),
    url: 'https://stream.coolwazobiainfo.com/cool-lagos',
  },
  {
    id: 3,
    title: 'WAZOBIA 95.1 FM',
    artist: 'LAGOS',
    artwork: require('../assets/img/wazobia.png'),
    url: 'https://stream.coolwazobiainfo.com/wazo-lagos',
  },
  {
    id: 4,
    title: 'MAX 102.3 FM',
    artist: 'LAGOS',
    artwork: require('../assets/img/max.png'),
    url: 'https://audiostreamer.gridpapaservers.com:2000/system/proxy.php?unique_id=MAXLAGOS&amp;mounturl=135.181.11.232:9193',
  },
  {
    id: 5,
    title: 'SMOOTH 98.1 FM',
    artist: 'LAGOS',
    artwork: require('../assets/img/smooth.png'),
    url: 'http://smoothlive.smooth981.fm:8000/smoothlivefm128',
  },
  {
    id: 6,
    title: 'RAY POWER 100.5 FM',
    artist: 'ABUJA',
    artwork: require('../assets/img/raypower.png'),
    url: 'https://streamlive2.hearthis.at:8000/9065169.ogg',
  },
  {
    id: 7,
    title: 'DREAM 92.5 FM',
    artist: 'ENUGU',
    artwork: require('../assets/img/dream.png'),
    url: 'https://ice31.securenetsystems.net/DREAM925FM',
  },
  {
    id: 8,
    title: 'HOT FM 93.3 FM',
    artist: 'LAGOS',
    artwork: require('../assets/img/hot.png'),
    url: 'https://streamer.radio.co/sa15bfd95d/listen',
  },
  {
    id: 9,
    title: 'RHYTHM 93.7 FM',
    artist: 'LAGOS',
    artwork: require('../assets/img/rhythm.png'),
    url: 'https://rhythmfmlagos-atunwadigital.streamguys1.com/rhythmfmjos',
  },
  {
    id: 10,
    title: 'ROYAL 95.1 FM',
    artist: 'LAGOS',
    artwork: require('../assets/img/royal.png'),
    url: 'http://197.210.168.147:8000/stream',
  },
  {
    id: 11,
    title: 'INSPIRATION 92.3 FM',
    artist: 'LAGOS',
    artwork: require('../assets/img/inspiration.png'),
    url: 'https://servoserver.com.ng/ifmlagoslive/live.mp3',
  },
  {
    id: 12,
    title: 'FRESH 105.9 FM',
    artist: 'IBADAN',
    artwork: require('../assets/img/fresh.png'),
    url: 'https://stream-67.zeno.fm/e9x2n97b9uduv?zs=8I-ZBUnpRImQUVMywb99aQ&an-uid=8567863976884764235',
  },
  {
    id: 13,
    title: 'BEAT 99.9 FM',
    artist: 'LAGOS',
    artwork: require('../assets/img/beat.png'),
    url: 'https://beatfmlagos-atunwadigital.streamguys1.com/beatfmlagos?listenerid=6f4e777d90cf29ed15546ecbd08391d6&awparams=playerid%3ASGplayer%3B&aw_0_1st.playerid=SGplayer&aw_0_1st.skey=1669629139229&us_privacy=1YNN&listenerid=6f4e777d90cf29ed15546ecbd08391d6&us_privacy=1YNN',
  },
  {
    id: 14,
    title: 'CLASSIC 97.3 FM',
    artist: 'LAGOS',
    artwork: require('../assets/img/classic.png'),
    url: 'http://classicfmlagos.atunwadigital.streamguys1.com/classicfmlagos',
  },
  {
    id: 15,
    title: 'NIGERIA INFO 92.3 FM',
    artist: 'PORT HARCOURT',
    artwork: require('../assets/img/Nigeria.png'),
    url: 'https://stream.coolwazobiainfo.com/niginf_ph',
  },
];

export default url;
