const url = [
  {
    id: 1,
    title: 'SALT TV',
    artist: 'ABAKALIKI',
    artwork: require('../assets/img/ebbc.png'),
    url: 'https://castor.streamthatvideo.co:8081/ebbc/tracks-v1a1/mono.m3u8',
  },
  {
    id: 2,
    title: 'ALJAZEERA',
    artist: 'DOHA, QATAR',
    artwork: require('../assets/img/aljazeera.png'),
    url: 'https://live-hls-web-aje.getaj.net/AJE/05.m3u8',
  },
  {
    id: 3,
    title: 'ARISE TV',
    artist: 'LAGOS',
    artwork: require('../assets/img/ariseTv.png'),
    url: 'https://news.ashttp9.visionip.tv/live/visiontvuk-news-arise-tv-hsslive-25f-16x9-SD/playlist.m3u8',
  },
  {
    id: 4,
    title: 'AFRO BEATS',
    artist: 'INTERNATIONAL',
    artwork: require('../assets/img/afroBeat.png'),
    url: 'https://stream.ecable.tv/afrobeats/index.m3u8',
  },
  {
    id: 5,
    title: 'BRIT TV',
    artist: 'INDIA',
    artwork: require('../assets/img/Brit_Asia_TV_logo.png'),
    url: 'https://a.jsrdn.com/broadcast/22693_4rGhgrBU/-0500/c.m3u8',
  },
  {
    id: 6,
    title: 'ABC',
    artist: 'LOS ANGELES',
    artwork: require('../assets/img/abc.jpg'),
    url: 'https://content.uplynk.com/channel/ext/2118d9222a87420ab69223af9cfa0a0f/kabc_24x7_news.m3u8',
  },
  {
    id: 7,
    title: 'VOICE AMERICA',
    artist: 'USA',
    artwork: require('../assets/img/voiceAmerica.jpg'),
    url: 'https://content.uplynk.com/channel/26bd482ffe364a1282bc3df28bd3c21f.m3u8',
  },
  {
    id: 8,
    title: 'BBC AMERICA',
    artist: 'AMERICA',
    artwork: require('../assets/img/bbcAmerica.png'),
    url: 'https://bcovlive-a.akamaihd.net/c9bf201b06694453bb29282f97191f58/us-east-1/6240731308001/playlist.m3u8',
  },
  {
    id: 9,
    title: 'BLOOMBERG TV',
    artist: 'USA',
    artwork: require('../assets/img/Bloomberg.png'),
    url: 'https://dai.google.com/linear/hls/event/NiumF4GTSGe-pXM-iMsP0A/master.m3u8',
  },
  {
    id: 10,
    title: 'CBS WUSA 90',
    artist: 'USA',
    artwork: require('../assets/img/cbs.png'),
    url: 'https://livevideo01.wusa9.com/hls/live/2015498/newscasts/live.m3u8',
  },
  {
    id: 11,
    title: 'EDGE SPORT',
    artist: 'USA',
    artwork: require('../assets/img/EDGE_SPORT.png'),
    url: 'https://edgesport-rakuten-samsung.amagi.tv/playlist.m3u8',
  },
  {
    id: 12,
    title: 'FOX 5 ATLANTA',
    artist: 'USA',
    artwork: require('../assets/img/fox.jpg'),
    url: 'https://csm-e-eb.csm.tubi.video/csm/extlive/tubiprd01,p-WAGA-Monetizer.m3u8',
  },
  {
    id: 13,
    title: 'LOVE WORLD',
    artist: 'USE',
    artwork: require('../assets/img/loveWorld.png'),
    url: 'https://cdn3.wowza.com/5/RGtVZkFxL3FOQkxX/lwut/ngrp:lwu.rtmp_all/playlist.m3u8',
  },
  {
    id: 14,
    title: 'DW',
    artist: 'USA',
    artwork: require('../assets/img/dw.png'),
    url: 'https://dacastmmd.mmdlive.lldns.net/dacastmmd/8e6d110b223b4aca9dd6f7c368baec07/playlist.m3u8',
  },
  {
    id: 15,
    title: 'NBC NEWS',
    artist: 'USA',
    artwork: require('../assets/img/NBC_News.png'),
    url: 'https://dai2.xumo.com/amagi_hls_data_xumo1212A-xumo-nbcnewsnow/CDN/master.m3u8',
  },
  {
    id: 16,
    title: 'METRO GLOBE',
    artist: 'USA',
    artwork: require('../assets/img/Metro.png'),
    url: 'https://edge.medcom.id/live-edge/smil:mgnch.smil/playlist.m3u8',
  },
  {
    id: 17,
    title: 'NASA TV',
    artist: 'USA',
    artwork: require('../assets/img/NASA_TV.png'),
    url: 'https://uplynkcontent.sinclairstoryline.com/channel/ddd76fdc1c0a456ba537e4f48e827d3e.m3u8',
  },
  {
    id: 18,
    title: 'TVC',
    artist: 'NIGERIA',
    artwork: require('../assets/img/tvc.jpg'),
    url: 'https://tvce.gridpapaservers.com/TVCSEPT/ngrp:myStream_all/playlist.m3u8',
  },
  {
    id: 19,
    title: 'DW INTERNATIONAL',
    artist: 'SPAIN',
    artwork: require('../assets/img/DWInternational.png'),
    url: 'https://dwamdstream102.akamaized.net/hls/live/2015525/dwstream102/index.m3u8',
  },
  {
    id: 20,
    title: 'CNBC AFRICA',
    artist: 'AFRICA',
    artwork: require('../assets/img/CNBC_Africa.png'),
    url: 'https://5be2f59e715dd.streamlock.net/CNBC/smil:CNBCSandton.smil/playlist.m3u8',
  },
  {
    id: 21,
    title: 'NTA',
    artist: 'NIGERIA',
    artwork: require('../assets/img/nta.png'),
    url: 'https://api.visionip.tv/live/ASHTTP/visiontvuk-entertainment-ntai-hsslive-25f-4x3-MB/playlist.m3u8',
  },
];

export default url;
